// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	newGame: (config: GameConfig) => typedError<Position, string>(__TAURI_INVOKE("new_game", { config })),
	makeMove: (uci: string) => typedError<Position, string>(__TAURI_INVOKE("make_move", { uci })),
	resign: () => typedError<GameRecord, string>(__TAURI_INVOKE("resign")),
	saveCompletedGame: () => typedError<GameRecord, string>(__TAURI_INVOKE("save_completed_game")),
	getPosition: () => typedError<Position, string>(__TAURI_INVOKE("get_position")),
	startEngine: () => typedError<boolean, string>(__TAURI_INVOKE("start_engine")),
	stopEngine: () => typedError<null, string>(__TAURI_INVOKE("stop_engine")),
	getEngineMove: (fen: string, depth: number | null, elo: number | null, skillLevel: number | null) => typedError<EngineMove, string>(__TAURI_INVOKE("get_engine_move", { fen, depth, elo, skillLevel })),
	analyzePosition: (fen: string, depth: number) => typedError<EngineEvaluation, string>(__TAURI_INVOKE("analyze_position", { fen, depth })),
	getOrCreatePlayer: (displayName: string) => typedError<Player, string>(__TAURI_INVOKE("get_or_create_player", { displayName })),
	updatePlayerSettings: (playerId: string, settings: PlayerSettings) => typedError<Player, string>(__TAURI_INVOKE("update_player_settings", { playerId, settings })),
	getGameReview: (gameId: string, depth: number) => typedError<MoveEvaluation[], string>(__TAURI_INVOKE("get_game_review", { gameId, depth })),
	getGameHistory: (limit: number, offset: number) => typedError<GameRecord[], string>(__TAURI_INVOKE("get_game_history", { limit, offset })),
	getCriticalMoments: (evaluations: MoveEvaluation[], isPlayerWhite: boolean) => __TAURI_INVOKE<CriticalMoment[]>("get_critical_moments", { evaluations, isPlayerWhite }),
	getPatternSummary: (evaluations: MoveEvaluation[], isPlayerWhite: boolean) => __TAURI_INVOKE<PatternSummary>("get_pattern_summary", { evaluations, isPlayerWhite }),
	getStudySuggestions: (summary: PatternSummary) => __TAURI_INVOKE<StudySuggestion[]>("get_study_suggestions", { summary }),
	analyzeHeuristics: (fen: string) => typedError<CoachingContext, string>(__TAURI_INVOKE("analyze_heuristics", { fen })),
	getLlmStatus: () => typedError<LlmStatus, string>(__TAURI_INVOKE("get_llm_status")),
	getAvailableModels: () => typedError<ModelStatus[], string>(__TAURI_INVOKE("get_available_models")),
	downloadModel: (modelId: string) => typedError<null, string>(__TAURI_INVOKE("download_model", { modelId })),
	generateCoaching: (fen: string, classification: string, coachingContext: {
	fen: string,
	phase: GamePhase,
	material: MaterialBalance,
	pawns: PawnStructure,
	activity: PieceActivity,
	kingSafety: KingSafety,
	tactics: TacticalMotif[],
	themes: PositionalTheme[],
} | null, playerMoveSan: string, engineBestSan: string | null, requestId: string | null) => typedError<CoachingResponse, string>(__TAURI_INVOKE("generate_coaching", { fen, classification, coachingContext, playerMoveSan, engineBestSan, requestId })),
	generateGameSummary: (result: string, outcomeType: string, moveCount: number, accuracyPct: number, bestMoves: number, blunders: number, mistakes: number, inaccuracies: number) => typedError<string, string>(__TAURI_INVOKE("generate_game_summary", { result, outcomeType, moveCount, accuracyPct, bestMoves, blunders, mistakes, inaccuracies })),
	/**  Evaluate a player's move during gameplay: engine analysis + classification + coaching text */
	evaluatePlayerMove: (fenBefore: string, fenAfter: string, isPlayerWhite: boolean, moveNumber: number, coachingLevel: CoachingLevel) => typedError<InGameCoachingFeedback, string>(__TAURI_INVOKE("evaluate_player_move", { fenBefore, fenAfter, isPlayerWhite, moveNumber, coachingLevel })),
	/**  Analyze the current position for pre-move hints (heuristic-only, no engine) */
	analyzePreMoveHints: (fen: string, previousPhase: "opening" | "middlegame" | "endgame" | null, coachingLevel: CoachingLevel, isPlayerWhite: boolean, opponentPersonality: 
/**  Prefers sharp, tactical play with king attacks */
"aggressive" | 
/**  Favors clean pawn structure and piece harmony */
"positional" | 
/**  Sets subtle traps and creates complications */
"trappy" | 
/**  Prioritizes safety and avoids risk */
"solid" | null) => typedError<PreMoveHint, string>(__TAURI_INVOKE("analyze_pre_move_hints", { fen, previousPhase, coachingLevel, isPlayerWhite, opponentPersonality })),
	loadNextPuzzle: (filter: PuzzleFilter) => typedError<PuzzleState, string>(__TAURI_INVOKE("load_next_puzzle", { filter })),
	getPuzzleState: () => typedError<{
	puzzle: Puzzle,
	/**  FEN after the opponent's setup move (player's turn) */
	startFen: string,
	/**  Which color the player is solving as */
	playerColor: string,
	/**  Legal destinations from the start position */
	legalDests: { [key in string]: string[] },
	/**  Total number of player moves expected */
	totalPlayerMoves: number,
	/**  Current move index (0-based, into the player moves) */
	currentMoveIndex: number,
} | null, string>(__TAURI_INVOKE("get_puzzle_state")),
	submitPuzzleMove: (uci: string) => typedError<PuzzleMoveResult, string>(__TAURI_INVOKE("submit_puzzle_move", { uci })),
	requestPuzzleHint: () => typedError<string | null, string>(__TAURI_INVOKE("request_puzzle_hint")),
	abandonPuzzle: () => typedError<PuzzleMoveResult, string>(__TAURI_INVOKE("abandon_puzzle")),
	savePuzzleResult: (solved: boolean) => typedError<null, string>(__TAURI_INVOKE("save_puzzle_result", { solved })),
	getPuzzleStats: () => typedError<PuzzleSessionStats, string>(__TAURI_INVOKE("get_puzzle_stats")),
	importPuzzlesFromCsv: (path: string, minRating: number, maxRating: number) => typedError<number, string>(__TAURI_INVOKE("import_puzzles_from_csv", { path, minRating, maxRating })),
	getPuzzleThemes: () => typedError<string[], string>(__TAURI_INVOKE("get_puzzle_themes")),
	getOpenings: (filter: RepertoireFilter) => typedError<Opening[], string>(__TAURI_INVOKE("get_openings", { filter })),
	getOpeningDetail: (openingId: string) => typedError<[Opening, OpeningPosition[]], string>(__TAURI_INVOKE("get_opening_detail", { openingId })),
	getRepertoire: (openingId: string) => typedError<RepertoireEntry[], string>(__TAURI_INVOKE("get_repertoire", { openingId })),
	addToRepertoire: (openingId: string, positionFen: string, moveUci: string, moveSan: string) => typedError<null, string>(__TAURI_INVOKE("add_to_repertoire", { openingId, positionFen, moveUci, moveSan })),
	removeFromRepertoire: (entryId: string) => typedError<null, string>(__TAURI_INVOKE("remove_from_repertoire", { entryId })),
	startRepertoireDrill: (openingId: string) => typedError<DrillState, string>(__TAURI_INVOKE("start_repertoire_drill", { openingId })),
	submitDrillMove: (uci: string) => typedError<DrillMoveResult, string>(__TAURI_INVOKE("submit_drill_move", { uci })),
	getDrillStats: () => typedError<DrillStats, string>(__TAURI_INVOKE("get_drill_stats")),
	importOpeningsFromJson: (path: string) => typedError<number, string>(__TAURI_INVOKE("import_openings_from_json", { path })),
	getSkillProfile: () => typedError<SkillProfile, string>(__TAURI_INVOKE("get_skill_profile")).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,ratings:v.data.ratings.map(i=>i)}) } : v) as typeof v)),
	getSkillRating: (category: string) => typedError<{
	id: string,
	playerId: string,
	category: string,
	rating: number,
	rd: number,
	volatility: number,
	gamesCount: number,
	lastUpdated: string,
} | null, string>(__TAURI_INVOKE("get_skill_rating", { category })).then((v) => ((v.status === "ok" ? { ...v, data: v.data==null?v.data:v.data } : v) as typeof v)),
	getDifficultyTarget: (category: string) => typedError<DifficultyTarget, string>(__TAURI_INVOKE("get_difficulty_target", { category })),
	/**
	 *  Get the opponent's move using personality-based selection.
	 * 
	 *  1. Runs multi-PV at full strength to find candidate moves
	 *  2. Analyzes each candidate's resulting position with heuristics
	 *  3. Scores candidates against personality weights + optional teaching bonus
	 *  4. Selects via softmax-weighted random choice
	 */
	getOpponentMove: (fen: string, depth: number | null, personality: PersonalityProfile, teachingMode: boolean, weakCategories: string[] | null) => typedError<SelectedMove, string>(__TAURI_INVOKE("get_opponent_move", { fen, depth, personality, teachingMode, weakCategories })),
	/**
	 *  Resolve the personality profile from an OpponentMode.
	 * 
	 *  - Choose: returns the explicitly provided personality
	 *  - Surprise: random selection
	 *  - CoachPicks: selects based on player's skill weaknesses
	 */
	resolvePersonality: (mode: OpponentMode, explicit: 
/**  Prefers sharp, tactical play with king attacks */
"aggressive" | 
/**  Favors clean pawn structure and piece harmony */
"positional" | 
/**  Sets subtle traps and creates complications */
"trappy" | 
/**  Prioritizes safety and avoids risk */
"solid" | null) => typedError<PersonalityProfile, string>(__TAURI_INVOKE("resolve_personality", { mode, explicit })),
	getDashboardData: () => typedError<DashboardData, string>(__TAURI_INVOKE("get_dashboard_data")).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,skillProfile:({...v.data.skillProfile,ratings:v.data.skillProfile.ratings.map(i=>i)})}) } : v) as typeof v)),
	checkAdaptiveDifficulty: () => typedError<AdaptivePrompt, string>(__TAURI_INVOKE("check_adaptive_difficulty")),
	getTheme: () => typedError<string, string>(__TAURI_INVOKE("get_theme")),
	setTheme: (theme: string) => typedError<null, string>(__TAURI_INVOKE("set_theme", { theme })),
};

/* Types */
export type AdaptivePrompt = {
	promptType: AdaptivePromptType,
	message: string,
	suggestion: string,
	targetActivity: string,
	targetCategory: string | null,
};

export type AdaptivePromptType = "increaseChallenge" | "decreaseChallenge" | "frustrationDetected" | "plateauDetected" | "none";

/**  Complete coaching context for a position */
export type CoachingContext = {
	fen: string,
	phase: GamePhase,
	material: MaterialBalance,
	pawns: PawnStructure,
	activity: PieceActivity,
	kingSafety: KingSafety,
	tactics: TacticalMotif[],
	themes: PositionalTheme[],
};

/**  How much coaching feedback to show during play */
export type CoachingLevel = 
/**  All feedback: pre-move hints + post-move for every classification */
"fullCoach" | 
/**  Post-move for inaccuracy+ and best; no pre-move hints */
"lightTouch" | 
/**  Only blunders */
"minimal" | 
/**  No in-game coaching */
"silent";

/**  A coaching response returned to the frontend */
export type CoachingResponse = {
	text: string,
	source: CoachingSource,
};

/**  Source of a coaching response */
export type CoachingSource = "cache" | "llm" | "template";

export type Color = "white" | "black";

/**  A pivotal moment in the game where the evaluation swung significantly */
export type CriticalMoment = {
	moveIndex: number,
	evalSwingCp: number,
	description: string,
	isPlayerMove: boolean,
};

export type DailyRecommendation = {
	text: string,
	targetActivity: string,
	targetCategory: string | null,
};

export type DashboardData = {
	skillProfile: SkillProfile,
	recentGames: GameRecord[],
	puzzleStats: PuzzleSessionStats,
	dailyRecommendation: DailyRecommendation,
	streak: SessionStreak,
};

export type DifficultyTarget = {
	targetRating: number,
	minRating: number,
	maxRating: number,
};

export type DrillMoveResult = {
	correct: boolean,
	correctMove: string | null,
	isComplete: boolean,
	entriesRemaining: number,
	explanation: string | null,
};

export type DrillState = {
	opening: Opening,
	currentEntry: RepertoireEntry,
	fen: string,
	opponentMove: string | null,
	playerColor: string,
	legalDests: { [key in string]: string[] },
	entriesTotal: number,
	entriesRemaining: number,
};

export type DrillStats = {
	totalDrills: number,
	totalCorrect: number,
	currentStreak: number,
	openingsDrilled: number,
};

/**  Full engine evaluation for a position */
export type EngineEvaluation = {
	score: Score,
	depth: number,
	/**  Principal variation (best line) as UCI moves */
	pv: string[],
	nodes: number,
	/**  Best move in UCI notation */
	bestMove: string,
};

/**  Result of requesting a move from the engine */
export type EngineMove = {
	uci: string,
	ponder: string | null,
};

export type EngineStrength = {
	/**  UCI_Elo value (1320–3190 for Stockfish) */
	elo: number,
	/**  Stockfish Skill Level (0–20) */
	skillLevel: number,
};

export type GameConfig = {
	playerColor: Color,
	engineStrength: EngineStrength,
	timeControl: TimeControl,
	coachingLevel?: CoachingLevel,
	opponentMode?: OpponentMode,
	personality?: PersonalityProfile | null,
	teachingMode?: boolean,
};

export type GameOutcome = ({ checkmate: {
	winner: Color,
} }) & { resignation?: never } | "stalemate" | "insufficientmaterial" | "threefoldrepetition" | "fiftymoverule" | ({ resignation: {
	winner: Color,
} }) & { checkmate?: never } | "draw";

/**  Game phase classification */
export type GamePhase = "opening" | "middlegame" | "endgame";

export type GameRecord = {
	id: string,
	playerId: string,
	pgn: string,
	result: string,
	playerColor: Color,
	engineElo: number,
	moveCount: number,
	startedAt: string,
	endedAt: string | null,
	timeControl: string,
	opponentPersonality: string | null,
	teachingMode: boolean,
};

/**  Post-move coaching feedback during gameplay */
export type InGameCoachingFeedback = {
	classification: MoveClassification,
	coachingText: string,
	evalBefore: Score,
	evalAfter: Score,
	engineBestUci: string,
	coachingContext: CoachingContext | null,
	moveNumber: number,
};

/**  Full king safety analysis */
export type KingSafety = {
	white: SideKingSafety,
	black: SideKingSafety,
};

/**  Status of the LLM subsystem */
export type LlmStatus = {
	available: boolean,
	modelLoaded: boolean,
	modelId: string | null,
	mode: string,
	device: string,
	bundled: boolean,
};

/**  Full material analysis */
export type MaterialBalance = {
	white: PieceCounts,
	black: PieceCounts,
	/**  Centipawn balance from white's perspective (positive = white ahead) */
	balanceCp: number,
	imbalances: MaterialImbalance[],
};

/**  Detected material imbalance */
export type MaterialImbalance = 
/**  One side has the bishop pair */
{ type: "bishopPair"; side: Side } | 
/**  Rook vs minor piece (bishop or knight) */
{ type: "exchangeUp"; side: Side } | 
/**  Minor piece + pawns vs rook */
{ type: "exchangeDown"; side: Side } | 
/**  Queen vs multiple minor pieces or rooks */
{ type: "queenVsPieces"; side: Side };

/**  Download/availability status of a single model */
export type ModelStatus = {
	id: string,
	displayName: string,
	downloaded: boolean,
	bundled: boolean,
	fileSizeMb: number,
	ramRequirementMb: number,
	systemMemoryMb: number,
	availableMemoryMb: number,
};

/**  Classification of a move's quality */
export type MoveClassification = "best" | "excellent" | "good" | "inaccuracy" | "mistake" | "blunder";

/**  Per-move evaluation for game review */
export type MoveEvaluation = {
	moveNumber: number,
	isWhite: boolean,
	fenBefore: string,
	playerMoveUci: string,
	playerMoveSan: string,
	engineBestUci: string | null,
	engineBestSan: string | null,
	evalBefore: Score | null,
	evalAfter: Score | null,
	classification: MoveClassification | null,
	depth: number,
	pv: string[],
	/**
	 *  Refutation line: the engine's PV for the position *after* the played
	 *  move (i.e. how the opponent punishes it), as UCI moves.
	 */
	refutationPv?: string[],
	coachingContext: CoachingContext | null,
	coachingText: string | null,
};

export type Opening = {
	id: string,
	name: string,
	eco: string,
	/**  Which color this opening is for */
	color: string,
	description: string,
	/**  Space-separated UCI moves: "e2e4 e7e5 g1f3" */
	moves: string,
	/**  Comma-separated theme tags */
	themes: string,
	difficulty: number,
};

export type OpeningPosition = {
	id: string,
	openingId: string,
	fen: string,
	moveIndex: number,
	parentFen: string | null,
	moveUci: string,
	moveSan: string,
};

/**  How the personality is selected at game start. */
export type OpponentMode = 
/**  Player picks from the 4 profiles */
"choose" | 
/**  Randomly assigned at game start */
"surprise" | 
/**  Picks the profile that best challenges the player's weaknesses */
"coachPicks";

/**  Summary of recurring patterns across a game's errors */
export type PatternSummary = {
	totalErrors: number,
	errorThemes: ([PositionalTheme, number])[],
	missedTactics: ([TacticType, number])[],
	errorsByPhase: Partial<{ [key in GamePhase]: number }>,
	strengths: string[],
};

/**  A chain of connected pawns */
export type PawnChain = {
	side: Side,
	/**  Squares of the pawns in this chain */
	squares: string[],
};

/**  Full pawn structure analysis */
export type PawnStructure = {
	white: SidePawnStructure,
	black: SidePawnStructure,
	chains: PawnChain[],
	/**  Files with no pawns at all */
	openFiles: string[],
	/**  Files with pawns of only one color */
	halfOpenFilesWhite: string[],
	halfOpenFilesBlack: string[],
};

/**  Personality profiles that make the AI opponent feel less engine-like. */
export type PersonalityProfile = 
/**  Prefers sharp, tactical play with king attacks */
"aggressive" | 
/**  Favors clean pawn structure and piece harmony */
"positional" | 
/**  Sets subtle traps and creates complications */
"trappy" | 
/**  Prioritizes safety and avoids risk */
"solid";

/**  Full piece activity analysis */
export type PieceActivity = {
	white: SideActivity,
	black: SideActivity,
};

/**  Activity summary for one piece */
export type PieceActivityDetail = {
	square: string,
	piece: string,
	mobility: number,
	isCentralized: boolean,
	isOnRim: boolean,
};

/**  Material counts for one side */
export type PieceCounts = {
	pawns: number,
	knights: number,
	bishops: number,
	rooks: number,
	queens: number,
};

export type Player = {
	id: string,
	displayName: string,
	createdAt: string,
	gamesPlayed: number,
	settings: PlayerSettings,
};

export type PlayerSettings = {
	/**  Default engine strength preset */
	preferredEngineElo?: number,
	/**  Board orientation preference */
	autoFlipBoard?: boolean,
	/**  Show evaluation bar during play */
	showEvalBar?: boolean,
	/**  Analysis depth for post-game review */
	reviewDepth?: number,
	/**
	 *  Override coaching level (beginner/intermediate/upperIntermediate).
	 *  If None, derived from game statistics.
	 */
	coachingLevel?: string | null,
	/**  In-game coaching intrusiveness level */
	inGameCoaching?: CoachingLevel,
};

/**  Position state sent to the frontend for rendering */
export type Position = {
	fen: string,
	turn: Color,
	/**  Legal destinations: maps "e2" → ["e3", "e4"] for chessground */
	dests: { [key in string]: string[] },
	lastMove: [string, string] | null,
	isCheck: boolean,
	isGameOver: boolean,
	outcome: GameOutcome | null,
	moveNumber: number,
	sanHistory: string[],
};

/**  High-level positional theme labels for template/LLM lookup */
export type PositionalTheme = "knightOnRim" | "bishopPairAdvantage" | "isolatedQueenPawn" | "passedPawn" | "doubledPawns" | "backwardPawn" | "openFile" | "rookOnSeventh" | "kingSafetyCompromised" | "undevelopedPieces" | "centralControl" | "pawnChainTension" | "materialImbalance" | "backRankWeakness" | "pinnedPiece" | "forkAvailable" | "hangingMaterial";

/**  Pre-move hint shown before the player's next move */
export type PreMoveHint = {
	hintText: string | null,
	hintType: PreMoveHintType,
	themes: PositionalTheme[],
};

/**  Category of pre-move hint */
export type PreMoveHintType = 
/**  Tactic available or hanging piece detected */
"tacticalAlert" | 
/**  Entering middlegame/endgame */
"phaseTransition" | 
/**  Positional theme to consider */
"strategicReminder" | 
/**  No hint to show */
"none";

export type Puzzle = {
	id: string,
	fen: string,
	/**  Space-separated UCI moves (first move is opponent's setup move) */
	solutionMoves: string,
	/**  Comma-separated theme tags */
	themes: string,
	category: PuzzleCategory,
	difficulty: number,
	sourceId: string | null,
	/**  JSON array of hint strings (up to 3 tiers) */
	hintsJson: string,
	explanation: string,
};

export type PuzzleCategory = "tactical" | "positional" | "endgame" | "opening" | "pattern";

/**  Filter criteria for loading puzzles */
export type PuzzleFilter = {
	category: PuzzleCategory | null,
	minDifficulty: number | null,
	maxDifficulty: number | null,
	themes: string[] | null,
};

/**  Result of submitting a move */
export type PuzzleMoveResult = {
	correct: boolean,
	isComplete: boolean,
	/**  Updated FEN after all applied moves (player + opponent response if any) */
	fen: string | null,
	/**  Legal dests for the next player move (if puzzle continues) */
	legalDests: { [key in string]: string[] } | null,
	/**  The last move played (for board highlight) [from, to] */
	lastMove: [string, string] | null,
	/**  Current move index after this action */
	currentMoveIndex: number,
	/**  Coaching explanation (only set when puzzle is complete) */
	explanation: string | null,
};

/**  Aggregate stats for the puzzle session */
export type PuzzleSessionStats = {
	totalAttempts: number,
	totalSolved: number,
	averageTimeMs: number,
	currentStreak: number,
	bestStreak: number,
};

/**  Sent to the frontend when a puzzle is loaded */
export type PuzzleState = {
	puzzle: Puzzle,
	/**  FEN after the opponent's setup move (player's turn) */
	startFen: string,
	/**  Which color the player is solving as */
	playerColor: string,
	/**  Legal destinations from the start position */
	legalDests: { [key in string]: string[] },
	/**  Total number of player moves expected */
	totalPlayerMoves: number,
	/**  Current move index (0-based, into the player moves) */
	currentMoveIndex: number,
};

export type RepertoireEntry = {
	id: string,
	playerId: string,
	openingId: string,
	positionFen: string,
	moveUci: string,
	moveSan: string,
	notes: string,
};

export type RepertoireFilter = {
	color: string | null,
	ecoPrefix: string | null,
	minDifficulty: number | null,
	maxDifficulty: number | null,
};

/**  Engine evaluation score */
export type Score = 
/**  Centipawn advantage (positive = white advantage) */
{ type: "cp"; value: number } | 
/**  Mate in N moves (positive = white mates, negative = black mates) */
{ type: "mate"; moves: number };

/**  The result of selecting an opponent move with personality. */
export type SelectedMove = {
	uci: string,
	personality: PersonalityProfile,
	personalityScore: number,
	teachingScore: number,
};

export type SessionStreak = {
	currentDays: number,
	longestDays: number,
	gamesToday: number,
	puzzlesToday: number,
};

/**  Which side a heuristic applies to */
export type Side = "white" | "black";

/**  Piece activity for one side */
export type SideActivity = {
	totalMobility: number,
	developedMinors: number,
	totalMinors: number,
	rookOnOpenFile: boolean,
	rookOnSeventh: boolean,
	pieces: PieceActivityDetail[],
};

/**  King safety for one side */
export type SideKingSafety = {
	kingSquare: string,
	pawnShieldCount: number,
	pawnShieldMax: number,
	hasCastled: boolean,
	canCastle: boolean,
	openFilesNearKing: number,
	kingZoneAttacks: number,
};

/**  Pawn structure analysis for one side */
export type SidePawnStructure = {
	isolated: string[],
	doubled: string[],
	passed: string[],
	backward: string[],
};

export type SkillProfile = {
	ratings: SkillRating[],
	overallRating: number,
	strongestCategory: string | null,
	weakestCategory: string | null,
};

export type SkillRating = {
	id: string,
	playerId: string,
	category: string,
	rating: number,
	rd: number,
	volatility: number,
	gamesCount: number,
	lastUpdated: string,
};

/**  A recommended study topic based on game weaknesses */
export type StudySuggestion = {
	topic: string,
	description: string,
	priority: number,
};

/**  Type of tactical motif */
export type TacticType = "pin" | "fork" | "skewer" | "hangingPiece" | "backRankThreat" | "discoveredAttack";

/**  A detected tactical motif */
export type TacticalMotif = {
	tacticType: TacticType,
	side: Side,
	/**  Square of the attacking/key piece */
	square: string,
	/**  Brief description for coaching */
	description: string,
};

export type TimeControl = {
	/**  Initial time in seconds (0 = unlimited) */
	initialSecs: number,
	/**  Increment per move in seconds */
	incrementSecs: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

