// Frontend-only display helpers for engine types. The types themselves are
// generated by tauri-specta — import them from "../api/bindings".
import type { MoveClassification, Score } from "../api/bindings";

/** Convert a Score to a display string */
export function formatScore(score: Score): string {
  if (score.type === "mate") {
    return score.moves > 0 ? `M${score.moves}` : `-M${Math.abs(score.moves)}`;
  }
  const value = score.value / 100;
  return value >= 0 ? `+${value.toFixed(1)}` : value.toFixed(1);
}

/** Convert a Score to a normalized 0-1 value for the eval bar (0.5 = equal) */
export function scoreToBarValue(score: Score): number {
  if (score.type === "mate") {
    return score.moves > 0 ? 1 : 0;
  }
  // Sigmoid-like scaling: ±500cp maps to roughly 0.1-0.9
  const cp = score.value;
  return 1 / (1 + Math.pow(10, -cp / 400));
}

/** Classification color mapping for UI — uses CSS tokens for theme support */
export const CLASSIFICATION_COLORS: Record<MoveClassification, string> = {
  best: "var(--cm-class-best)",
  excellent: "var(--cm-class-excellent)",
  good: "var(--cm-class-good)",
  inaccuracy: "var(--cm-class-inaccuracy)",
  mistake: "var(--cm-class-mistake)",
  blunder: "var(--cm-class-blunder)",
} as const;
