// Frontend-only game constants. The game types themselves are generated by
// tauri-specta — import them from "../api/bindings".
import type { EngineStrength } from "../api/bindings";

export const ENGINE_PRESETS = {
  beginner: { elo: 1350, skillLevel: 1 } satisfies EngineStrength,
  intermediate: { elo: 1800, skillLevel: 8 } satisfies EngineStrength,
  advanced: { elo: 2200, skillLevel: 14 } satisfies EngineStrength,
  maximum: { elo: 3190, skillLevel: 20 } satisfies EngineStrength,
} as const;
